config/routes.rb
Rails.application.routes.draw do

  get 'password_reset/new'
  get 'password_reset/edit'
  root 'static_pages#home'
  get 'home',   to: 'static_pages#home'
  get 'help',   to: 'static_pages#help'
  get 'about',  to: 'static_pages#about'
  get 'signup', to: 'users#new'
  get 'login',  to: "sessions#new"
  post 'login', to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users do
    member do
      get :schools, :entered_schools, :following, :followers
    end
  end
  resources :schools do
    member do
      get :belonging_students
    end
  end
  resources :user_relationships do
    member do
      get :following, :followers
    end
  end
  resources :retweets, only: [:create, :destroy]
  resources :school_chats, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :school_relationships, only: [:create, :destroy]
  resources :user_relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def new
  end
  
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "パスワード再設定用のメールを送信しました"
      redirect_to root_url
    else
      flash.now[:danger] = "Eメールが見つかりませんでした"
      render "new"
    end
  end

  def edit
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "パスワードの更新に成功しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
  
  def get_user
    @user = User.find_by(email: params[:email])
  end
  
  def valid_user
    unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
      redirect_to root_url
    end
  end
  
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "有効期限切れです"
      redirect_to new_password_reset_path
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.slim
  - provide(:title, "パスワードのリセット")
  h1 パスワードのリセット

  .row
    .col-md-6.col-md-offset-3
      = form_for( @user, url: password_resets_path(params[:id]) ) do |f|
        == render "shared/error_messages", object: f.object
        
        = hidden_field_tag :email, @user.email
        
        = f.label :password, "新しいパスワード"
        = f.password_field :password, class: "form-control"
        
        = f.label :password_confirmation, "新しいパスワード（確認）"
        = f.password_field :password_confirmation, class: "form-control"
        
        = f.submit "更新する", class: "btn btn-primary"

app/views/password_resets/new.html.slim
  - provide(:title, "パスワードの再設定")
  h1 パスワードの再設定

  .row
    .col-md-6.col-md-offset-3
      = form_for(:password_reset, url: password_resets_path ) do |f|
        = f.label :email, "Eメール"
        = f.email_field :email, class: "form-control"
      
        = f.submit "保存する", class: "btn"
      