config/routes.rb
Rails.application.routes.draw do

  get 'password_reset/new'
  get 'password_reset/edit'
  root 'static_pages#home'
  get 'home',   to: 'static_pages#home'
  get 'help',   to: 'static_pages#help'
  get 'about',  to: 'static_pages#about'
  get 'signup', to: 'users#new'
  get 'login',  to: "sessions#new"
  post 'login', to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users do
    member do
      get :schools, :entered_schools, :following, :followers
    end
  end
  resources :schools do
    member do
      get :belonging_students
    end
  end
  resources :user_relationships do
    member do
      get :following, :followers
    end
  end
  resources :retweets, only: [:create, :destroy]
  resources :school_chats, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :school_relationships, only: [:create, :destroy]
  resources :user_relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.slim
  - if object.errors.any?
    #error_explanation
      .alert.alert_danger
        = "#{object.errors.count}つのエラーがあります"
      ul
        - object.errors.full_messages.each do |msg|
          li = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.feed_items
    == render @feed_items
  = paginate @feed_items

app/views/shared/_miniforms.html.slim
.miniforms
  == render 'school_relationships/enter_form'
  == render 'retweets/retweet_form'

app/views/shared/_school_chat_form.html.slim
.chat-form
  = form_for(@school_chats_build) do |f|
    input type="hidden" name="school_chat[school_id]" id="school_chat_school_id" value="#{@school.id}"
    
    = f.label :content, "コメント"
    = f.text_area :content, class: "materialize-textarea"
    = f.submit "投稿する", class: "btn waves-effect waves-light right"

app/views/shared/_school_modal.html.slim
.school-modal
  a class="wave-effect waves-light btn modal-trigger" href="#school-modal_form"
    | 投稿する
div id="school-modal_form" class="modal"
  = form_for(@school_build) do |f|
    .modal-content
      == render 'shared/error_messages', object: f.object
  
      = f.label :name, "学校名"
      = f.text_field :name
        
      = f.label :sub_title, "サブタイトル（任意）"
      = f.text_field :sub_title, placeholder: "アピールポイント等を記入"
      
      = f.label :content, "学校について（任意）"
      = f.text_area :content, class: "materialize-textarea", placeholder: "設立する学校の特徴など"
      
      span.picture
        = f.label :picture, "学校写真"
        = f.file_field :picture
      
    .modal-footer
      i.material-icons.left
        | access_time
      p = Time.current.to_date
      p 
        = image_tag(current_user.user_image.url, class: "school-user_image")
        | #{current_user.name}
      button class="btn waves-effect waves-light" type="submit" name="commit"
        | 提出する
        i class="material-icons right"
          | send
      
javascript:
  $('#school_picture').bind('change', function(){
    var size_in_megabytes = this.file[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('5MB以上の写真は使用できません');
    }
  });

app/views/shared/_sidebar.html.slim
aside.col.s4.sidebar.hide-on-small-only
  - if logged_in?
    .sidebar-partials
      == render 'shared/user_info'
      == render 'shared/school_modal'
    == render 'shared/sidebar_nav_after_login'
  - else
    == render 'shared/sidebar_nav_before_login'

app/views/shared/_sidebar_nav_after_login.html.slim
ul.sidebar-nav
  li = link_to root_path do
    i.material-icons home
    | ホーム
  li = link_to schools_path do
    i.material-icons business
    | 学校一覧
  li = link_to current_user do
    i.material-icons account_circle
    | プロフィール
  li = link_to edit_user_path(current_user) do
    i.material-icons folder_shared
    | 設定
  li.divider
  li = link_to logout_path, method: "delete" do
    i.material-icons exit_to_app
    | ログアウト

app/views/shared/_sidebar_nav_before_login.html.slim
ul.sidebar-nav
  li = link_to root_path do
    i.material-icons home
    | ホーム
  li = link_to schools_path do
    i.material-icons business
    | 学校一覧
  li = link_to help_path do
    i.material-icons help
    | ヘルプ
  li.divider
  li = link_to login_path do
    i.material-icons person_pin
    | ログイン

app/views/shared/_stats.html.slim
- if @user ||= current_user
  .stats
    .stats-info
      .stats-header
        i.material-icons school
      .stats-container
        a href="#{schools_user_path(@user)}"
          strong id="schools" class="stats-count"
            = @user.schools.count
          | 投稿
        a href="#{entered_schools_user_path(@user)}"
          strong id="entered_schools" class="stats-count"
            = @user.entered_schools.count
          | お気に入り
    .stats
      .stats-header
        i.material-icons people
      .stats-container
        a href="#{followers_user_path(@user)}"
          strong id="followers" class="stats-count"
            = @user.followers.count
          | フォロワー
        a href="#{following_user_path(@user)}"
          strong id="following" class="stats-count"
            = @user.following.count
          | フォロー

app/views/shared/_stats_schools.html.slim
ul.schools
  - @schools.each do |school|
    li id="school-#{ school.id }"
      .schools-header
        = image_tag school.picture.url, class: "schools-header_picture" if school.picture?
        .schools-titles
           span.subtitle
             = link_to school.sub_title, school
           p.name
             = link_to school.name, school
        - if school.user == current_user
          a class="stats-dropdown_trigger trigger" data-id="#dropdown-content_#{school.id}" alt="学校操作メニュー"
            i.material-icons arrow_drop_down
          ul class="stats-dropdown_content" id="dropdown-content_#{school.id}"
            li
              = link_to school, class: "delete",  method: 'delete', data: { confirm: "本当に削除しますか?" } do
               i.material-icons delete_forever
               | 削除
            li
              = link_to edit_school_path(school) do
                i.material-icons edit
                | 編集
            li.divider
            li
              a class="trigger" data-id="#dropdown-content_#{school.id}"
                i.material-icons arrow_upward
                | 閉じる

app/views/shared/_stats_users.html.slim
ul.users
  - @users.each do |user|
    li id="user-#{ user.id }"
      .users-header
        = link_to image_tag(user.user_image.url, class: "users-header_image"), user
        .users-name
           span.unique_name
             = link_to user.unique_name, user
           p.name
             = link_to user.name, user

app/views/shared/_user_info.html.slim
section.user-info
  = link_to image_tag(current_user.user_image.url, class: "user-info_image"), current_user
  h1.name
    = current_user.name
    p.unique_name 
      | @#{current_user.unique_name}