config/routes.rb
Rails.application.routes.draw do

  get 'password_reset/new'
  get 'password_reset/edit'
  root 'static_pages#home'
  get 'home',   to: 'static_pages#home'
  get 'help',   to: 'static_pages#help'
  get 'about',  to: 'static_pages#about'
  get 'signup', to: 'users#new'
  get 'login',  to: "sessions#new"
  post 'login', to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users do
    member do
      get :schools, :entered_schools, :following, :followers
    end
  end
  resources :schools do
    member do
      get :belonging_students
    end
  end
  resources :user_relationships do
    member do
      get :following, :followers
    end
  end
  resources :retweets, only: [:create, :destroy]
  resources :school_chats, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :school_relationships, only: [:create, :destroy]
  resources :user_relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.slim
footer.footer
  nav
    .nav-wrapper
      = link_to root_path, id: "logo", class: "footer-logo" do
        | Schoop
      .to-header#to-header
      

app/views/layouts/_header.html.slim
header.header
    nav
      .nav-wrapper
        = link_to root_path, id: "logo", class: "header-logo" do
          | Schoop
        .current-location
          i.material-icons.left chevron_right
          span.title.left = yield(:title)
        ul.right.hide-on-small-only
          li = link_to root_path, alt: "ホーム画面に遷移する" do
            i.material-icons home
          li = link_to help_path, alt: "ヘルプに遷移する" do
            i.material-icons help
          li = link_to schools_path do
            i.material-icons business
          - if logged_in?
            li
              a href="#!" class="dropdown-trigger" data-target="header-dropdown"
                = current_user.name
                i class="material-icons right" arrow_drop_down
            ul class="dropdown-content" id="header-dropdown"
              li = link_to "プロフィール", current_user
              li = link_to "設定", edit_user_path(current_user.id)
              li.divider
              li = link_to "ログアウト", logout_path, method: "delete"
          - else
            li = link_to "ログイン", login_path
            li = link_to "アカウント登録", signup_path
            

app/views/layouts/_sidebar_nav_before_log_in.html.slim
.sidebar-logo
  = link_to "Schoop", root_path, class: "logo"
ul.sidebar-nav
  li = link_to root_path do
    i.material-icons home
    | ホーム
  li = link_to help_path do
    i.material-icons help
    | ヘルプ
  li.divider
  li = link_to login_path do
    i.material-icons person_pin
    | ログイン

app/views/layouts/_sidenav_after_log_in.html.slim
.sidenav-partials
  == render 'shared/user_info'
  == render 'shared/school_modal'
  == render 'shared/stats'
ul.sidebar-nav
  li = link_to root_path do
    i.material-icons home
    | ホーム
  li = link_to current_user do
    i.material-icons account_circle
    | プロフィール
  li = link_to edit_user_path(current_user) do
    i.material-icons folder_shared
    | 設定
  li.divider
  li = link_to logout_path, method: "delete" do
    i.material-icons exit_to_app
    | ログアウト

app/views/layouts/_sidenav_before_log_in.html.slim
.sidenav-partials
  .sidebar-logo
    = link_to "Schoop", root_path, class: "logo"
ul.sidebar-nav
  li = link_to root_path do
    i.material-icons home
    | ホーム
  li = link_to help_path do
    i.material-icons help
    | ヘルプ
  li.divider
  li = link_to login_path do
    i.material-icons person_pin
    | ログイン

app/views/layouts/_slidebar_after_log_in.html.slim
.sidebar-logo
  = link_to "Schoop", root_path, class: "logo"
.sidebar-partials
  == render 'shared/user_info'
  == render 'shared/school_modal'
ul.sidebar_nav
  li = link_to root_path do
    i.material-icons home
    | ホーム
  li = link_to schools_path do
    i.material-icons business
    | 学校一覧
  li = link_to current_user do
    i.material-icons account_circle
    | プロフィール
  li = link_to edit_user_path(current_user) do
    i.material-icons folder_shared
    | 設定
  li.divider
  li = link_to logout_path, method: "delete" do
    i.material-icons exit_to_app
    | ログアウト

app/views/layouts/_slidebar_before_log_in.html.slim
.sidebar-logo
    = link_to "Schoop", root_path, class: "logo", id: "logo"
ul.slidebar-nav.sidebar_nav
  li = link_to root_path do
    i.material-icons home
    | ホーム
  li = link_to schools_path do
    i.material-icons business
    | 学校一覧
  li = link_to help_path do
    i.material-icons help
    | ヘルプ
  li.divider
  li = link_to login_path do
    i.material-icons person_pin
    | ログイン

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    = csrf_meta_tags 
    = csp_meta_tag 

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'true'


  body
    == render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag :div, message, class: "alert alert-#{message_type}"
      == yield
    == render 'layouts/footer'
    ul id="slide-out" class="sidenav slidebar sidebar"
      - if logged_in?
        == render 'layouts/slidebar_after_log_in'
      - else
        == render 'layouts/slidebar_before_log_in'
    a data-target="slide-out" class="sidenav-trigger show-on-small"
      i class="material-icons"
         | menu

javascript:
  var content = $("div.col");
  var smWindowSize = 600;
  
  $(function(){
    // DOM取得時にウィンドウ幅が600px以下だった場合にcol.s12に置き換える
    if (window.innerWidth <= smWindowSize){
      materializeConvertClass(content, "s8", "s12");
    }
  });
  
  //school slide menu
  //triggerをクリック時、dropdown_contentを表示
  $('.trigger').on('click',function(){
    var content = $(this).data('id');
    $(content).slideToggle(50);
  });
  
  var homeExplanation = document.getElementById("home-explanation").offsetTop;
  var home = document.getElementById("home");
  window.onscroll = function(){
    if (window.pageYOffset > 0) {
      var opacity = (window.pageYOffset / homeExplanation) * 2;
      console.log(opacity);
      home.style.background = "linear-gradient(rgba(255, 255, 255, "+ opacity +"), rgba(255, 255, 255, "+ opacity +")), url(/assets/home-a2d887ff6e2c6abbd5622c4825d3b98fa93ee9c0da7b34232ddd200e17e158f9.jpg)";
    }
  }
    
  